-- AlterTable
ALTER TABLE "Profile"
ADD COLUMN "height" TEXT NOT NULL DEFAULT '',
ADD COLUMN "languages" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "availability" TEXT NOT NULL DEFAULT 'Unavailable',
ADD COLUMN "verified" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "experienceYears" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "rating" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "services" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
